function [ANGLE_IN_RADS TIME_IN_SECONDS]=Antenna_Separation_To_Phase_Time(OPERATIONS_CENTER_FREQUENCY,SEPARATION_IN_INCHES)
    %OPERATIONS_CENTER_FREQUENCY SHOULD BE INPUT IN GHZ
    %I.E. OPERATIONS_CENTER_FREQUENCY=2.4 YEILDS 2.4 GHz
    C=299792458; M_PER_IN=2.54*0.01;
    lAMBDA=C/(OPERATIONS_CENTER_FREQUENCY*1E9);
    CYCLES=(SEPARATION_IN_INCHES*M_PER_IN)/lAMBDA;
    
    ANGLE_IN_RADS=CYCLES*2*pi;
    TIME_IN_SECONDS=CYCLES/(OPERATIONS_CENTER_FREQUENCY*1E9);
end